# These are supported funding model platforms

github: [ANAMIZED]
custom:
  - "https://donate.stripe.com/00w5kE3wOg5L8Jn2F243S00"
  - "https://buy.stripe.com/3cI14o8R8dXD3p3frO43S04"
  - "https://buy.stripe.com/bJecN63wObPv6Bf7Zm43S02"
  - "https://basescan.org/address/0xD3d0E9eDAe3Ac7bb199a8EAA761BdA423b878438"
  - "https://solscan.io/account/ETQwWf19axArsY493UfC6bxe2BmEzmzvCb58PPnC38A"
